output "vpc_id" {
  value = module.vpc.vpc_id
}

output "private_subnets" {
  value = module.vpc.private_subnets
}



// DNS
//
# output "dns_acme_zone_id" {
#   value = var.dns_enabled ? module.dns[0].acme_zone_id : null
# }

# output "dns_main_name_servers" {
#   value = var.dns_enabled ? module.dns[0].main_name_servers : null
# }
# output "dns_acme_zone_role_arm" {
#   value = var.dns_enabled ? module.dns[0].acme_zone_role_arm : null
# }


//RDS
//
# output "rds_cluster_endpoint" {
#   value = var.rds_enabled ? module.rds_aurora[0].end_point : null
# }


# output "auth_server_issuer" {
#   value = module.okta_auth_server.auth_server_issuer
# }


# EKS

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "kubernetes_node_groups" {
  value = module.eks.kubernetes_node_groups
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubectl_config
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "cluster_arn" {
  description = "Kubernetes Cluster ARN"
  value       = module.eks.cluster_arn
}

output "cluster_role" {
  description = "Cluster role name"
  value       = module.eks.cluster_role

}

output "kubernetes_endpoint" {
  value = module.eks.kubernetes_endpoint
}

